const TABLE_HEAD = ['#', 'Word', 'Phonetic', 'Type', 'Meaning', 'Definition', 'Example'];

export function renderVocabularyReadme(manifest, words) {
  const sections = [
    '<!-- Generated by "npm run build" from words-*.json. Do not edit by hand. -->',
    `# ${escapeText(manifest.title)}`,
    escapeText(manifest.description),
    renderFacts(manifest),
    renderRelated(manifest),
    renderTable(manifest, words),
    `Source: ${escapeText(manifest.source)}`,
  ];
  return `${sections.filter(Boolean).join('\n\n')}\n`;
}

function renderFacts(manifest) {
  const facts = [
    `**Level** ${manifest.level}`,
    `**Words** ${manifest.wordCount}`,
    `**Languages** ${manifest.sourceLang} → ${manifest.targetLang}`,
    `**Version** ${manifest.version}`,
    `**License** ${escapeText(manifest.license)}`,
  ];
  return facts.join(' · ');
}

function renderRelated(manifest) {
  const links = (manifest.relatedPacks ?? []).map((related) => {
    const pair = `${manifest.sourceLang}-${manifest.targetLang}`;
    return `[${related.type}: ${related.id}](../../../${related.type}/${pair}/${related.id}/)`;
  });
  return links.length > 0 ? `Related: ${links.join(', ')}` : '';
}

function renderTable(manifest, words) {
  const head = TABLE_HEAD.map((label) => (label === 'Meaning' ? `Meaning (${manifest.targetLang})` : label));
  const rows = words.map((entry, index) => renderRow(entry, index + 1));
  return [renderLine(head), renderLine(head.map(() => '---')), ...rows].join('\n');
}

function renderRow(entry, number) {
  return renderLine([
    String(number),
    `**${escapeText(entry.word)}**`,
    escapeText(entry.phonetic ?? ''),
    escapeText(entry.pos ?? ''),
    escapeText(entry.translation ?? ''),
    escapeText(entry.definition ?? ''),
    renderExample(entry),
  ]);
}

function renderExample(entry) {
  const sentence = escapeText(entry.exampleSentence ?? '');
  const translation = escapeText(entry.exampleTranslation ?? '');
  if (sentence && translation) return `${sentence}<br><i>${translation}</i>`;
  return sentence || translation;
}

function renderLine(cells) {
  return `| ${cells.join(' | ')} |`;
}

function escapeText(value) {
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/\|/g, '\\|')
    .replace(/\s*\n\s*/g, ' ')
    .trim();
}
